blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://python-package-template-pypi.readthedocs.io/en/latest/
    about: Please check the documentation before opening an issue.
  - name: PyPA Code of Conduct
    url: https://www.pypa.io/en/latest/code-of-conduct/
    about: Please read and follow the PyPA Code of Conduct.
